name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Show working dir
      run: pwd
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev
    - name: Build and push image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ethanabrace/blog-site
        tags: latest
        registry: docker.io
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Production server SSH Private Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          known_hosts: 'placeholder'
      - name: Add known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - uses: actions/checkout@v2
      - name: Copy Deploy files to server
        run: scp $(pwd)/deploy.sh $(pwd)/docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/docker/${{ secrets.SSH_HOST }}/
      - name: Run Deploy script
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} ~/docker/${{ secrets.SSH_HOST }}/deploy.sh



